---
- hosts: all
  become: yes
  tasks:
    - name: use tags
      tags: first
      apt: 
        name: apache2
        state: present
    - name: tags again
      tags: second
      service:
        name: apache2
        state: started
    - name: tags yeah
      tags: third
      apt:
        name: apache2
        state: absent
        purge: yes
        autoremove: yes 
