---
- hosts: all
  become: yes
  tasks:
    - name: Demo Playbook
      apt: 
        name: apache2 
        state: present

    - name: Demo for starting service
      service: 
        name: apache2 
        state: started
